### ISSUE TITLE
Update Fabric-CLI tool for end-to-end data transfer testing

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#101]
We need to update the `fabric-cli` tool to use the modified Fabric Interoperation Node SDK API.

**Comment by sanvenDev** [comment]
This is completed right?

**Comment by VRamakrishna** [comment]
Fixed in https://github.com/hyperledger-labs/weaver-dlt-interoperability/pull/105
