### ISSUE TITLE
go sdk for exercising asset exchange

### ISSUE THREAD

**Issue by knarayan** [hyperledger-labs/weaver-dlt-interoperability#107]
The equivalent code for the node sdk files `AssetManager.ts` and `InteroperableHelper.ts` and their dependencies will be ported to go sdk via this issue.

**Comment by sanvenDev** [comment]
@knarayan can we close this?

**Comment by knarayan** [comment]
Addressed via the PR https://github.com/hyperledger-labs/weaver-dlt-interoperability/pull/116 . Closing.
