### ISSUE TITLE
test: fix network-setup failed to normalize chaincode path

### ISSUE THREAD

**Issue by petermetz** [hyperledger-labs/weaver-dlt-interoperability#109]
## To reproduce

Follow the steps here:
https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/#fabric-network
Once you reach the part that says `make start-interop` it fails with this error:

```sh
Error: failed to normalize chaincode path: 'go list' failed with: go: github.com/golang/protobuf@v1.5.2: missing go.sum entry; to add it:
        go mod download github.com/golang/protobuf: exit status 1
!!!!!!!!!!!!!!! Chaincode packaging on peer0.org1 has failed !!!!!!!!!!!!!!!!

ERROR !!! Deploying chaincode failed
make: *** [Makefile:20: start-network1] Error 1
```

### Complete Log Output

[weaver-hl-lab-test-network-setup-chaincode-fail-2021-07-12.log](https://github.com/hyperledger-labs/weaver-dlt-interoperability/files/6804668/weaver-hl-lab-test-network-setup-chaincode-fail-2021-07-12.log)

### Operating System

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

### ProtoC Version

```sh
$ protoc --version
libprotoc 3.15.6
```

### Go Version

```sh
$ go version
go version go1.16.5 linux/amd64
```

**Comment by VRamakrishna** [comment]
@sanvenDev Isn't the start script supposed to run a `go mod tidy`? If not, let's just check in a `go.sum`.
