### ISSUE TITLE
Write instructions to start testnets with dockerized relays and drivers

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#133]
Fill https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/test-network/setup-local-docker and https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/test-network/setup-packages-docker.

**Comment by sanvenDev** [comment]
`setup-local-docker` is still pending.
