### ISSUE TITLE
Control access to policy and membership recording functions in Fabric Interop CC

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#140]
Currently, any network client can create a new access control or verification policy, or overwrite an existing one. We need to add access control checks and enforcement mechanisms so only "privileged" users are allowed to perform these tasks. The same consideration applied to recording foreign networks' membership certificates.

**Comment by petermetz** [comment]
@VRamakrishna Is this about access control in the web layer (HTTP/JWT header for example) or is it inside the logic of the chain code, dealing with Fabric MSP identities? (Just curious)

**Comment by VRamakrishna** [comment]
@petermetz This particular feature is about adding access control rules within chaincode logic. And yes, it's needed to distinguish Fabric MSP identities so we can regulate who is allowed to record policies (via a transaction submitted to the Fabric Interop Chaincode) to the channel and who is not. Our idea is simply to use special attributes embedded in the clients' certificates; the presumption is that an MSP will issue certificates with such attributes to a client only after suitable vetting. Incidentally, this is the presumption behind a Fabric driver's enrollment in the network too; the driver is treated as a special category of client.

Depending on the nature of the Fabric network's deployment, we can enforce such access control differently. If the chaincode is assumed to be heavily guarded, so that nobody can hit the chaincode interface without getting privileged access at the web layer itself, then putting in the right access policies in the web layer will also solve this problem. But we are choosing to go with an in-chaincode access control mechanism because it's more general, and frankly, simpler for us to implement at this point.

**Comment by VRamakrishna** [comment]
NOTE: we need to limit access control policy updates for PDC data to PDC owners.

**Comment by VRamakrishna** [comment]
Done for membership recording and updates in #316 . Policies recording guards are still pending.
