### ISSUE TITLE
Golang Chaincodes: Units Tests in different package.

### ISSUE THREAD

**Issue by sanvenDev** [hyperledger-labs/weaver-dlt-interoperability#156]
1. Rename package name for unit tests by suffixing `_test` to the main package name.
2. Modify the test files so that they import the chaincode and then call functions using the namespace of the import.

**Comment by sanvenDev** [comment]
It seems this way the private functions can not be tested, and hence there will be a mix of test cases, one for exported functions in `_test` package, and others in main package to test private functions.
 
So instead shall we close this issue and leave it as it is? @VRamakrishna

**Comment by VRamakrishna** [comment]
I agree. Closing.
