### ISSUE TITLE
Setting up Corda components for local Weaver failed

### ISSUE THREAD

**Issue by tnkhanh** [hyperledger-labs/weaver-dlt-interoperability#167]
I'm setting up Weaver locally with instructions from https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/test-network/setup-local/
At "Corda Components/Interoperation Cordapp" on that page, `make build-local` failed:

```
      > Could not resolve com.weaver:protos-java-kt:1.2.3.
         > Could not get resource 'https://dl.bintray.com/arrow-kt/arrow-kt/com/weaver/protos-java-kt/1.2.3/protos-java-kt-1.2.3.pom'.
            > Could not GET 'https://dl.bintray.com/arrow-kt/arrow-kt/com/weaver/protos-java-kt/1.2.3/protos-java-kt-1.2.3.pom'. Received status code 403 from server: Forbidden

```
It looks like since jcenter and bintray is going down recently, the build cannot download packages from bintray and fails.
Is there a solution for this?

Thanks,
Khanh

**Comment by VRamakrishna** [comment]
Can you comment out the following line and re-run `make build-local`?
- https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/core/network/corda-interop-app/build.gradle.local#L54

@sanvenDev Do we need the dependency even in the local gradle build?

**Comment by tnkhanh** [comment]
> Can you comment out the following line and re-run `make build-local`?
> 
>     * https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/core/network/corda-interop-app/build.gradle.local#L54
> 
> 
> @sanvenDev Do we need the dependency even in the local gradle build?

Thanks, I tried that. It gives this error

```
* What went wrong:                                        
Execution failed for task ':interop-contracts:compileKotlin'.                                                                         
> Could not resolve all files for configuration ':interop-contracts:compileClasspath'.                                                                                          
   > Could not find com.weaver:protos-java-kt:1.2.3.                                         
     Searched in the following locations:
   [.. sites they searched for  ..]

     Required by:                                 
         project :interop-contracts                                                                        
```
I think it needs the `com.weaver:protos-java-kt:1.2.3` and it is on bintray

**Comment by tnkhanh** [comment]
> @tnkhanh are you running `make build` in `common/protos-java-kt` folder, before building Interoperation Cordapp using `make build-local`?
> 
> Alternatively you can create `github.properties` from `github.properties.template`, and then run `make build`. Our packages are published in Github maven repositories (not on bintray) so you need above file, if you want to use published packages.

Wow, it is working now. Thanks a lot!
