### ISSUE TITLE
Protos Package for RUST

### ISSUE THREAD

**Issue by sanvenDev** [hyperledger-labs/weaver-dlt-interoperability#174]
Currently we copy the protos using script during build from `common/protos` to `core/relay/protos` folder.

Goal is to create a protos package/tool for RUST, that can be directly imported by Relay code.
We do something similar for other languages, and we have `common/protos-go`, `common/protos-js`, and `common/protos-java-kt` folders for that.
Let's have `common/protos-rs` as well, then in `core/relay` we can have:
`make build`: Can use published `protos-rs` module in some cargo registry (if possible).
`make build-local`: Can copy/import from local compiled `common/protos-rs` version.

**Comment by VRamakrishna** [comment]
@GGabi Any updates?

**Comment by VRamakrishna** [comment]
We should support 2 modes for relay-building; one from the local clone of the repo (`common/protos-rs` folder) and another by depending on a package published to `crates.io`.

**Comment by GGabi** [comment]
Sorry for the late reply, I've been swamped at work lately.
Last I checked I have managed to get a `protos-rs` package compiling just like all the other non-rust versions and configured `relay` to compile from the local package with `build local`.
Going forward I will continue trying to get `relay`s remote `build` working as it did before.
