### ISSUE TITLE
Unable to push commit

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#2]
I created a branch called `init` with a code and documents bundle and ran the following command after committing locally:
```
git push --set-upstream origin init
```
Here is what I got (I entered my username and github.com account password):
```
Username for 'https://github.com': VRamakrishna
Password for 'https://VRamakrishna@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/hyperledger-labs/weaver-dlt-interoperability.git/'

**Comment by tkuhrt** [comment]
Hi, @VRamakrishna : I am not sure what I can do to help. It appears that you are unable to log into github. One thing that you might check is whether you have two-factor authentication set up. If so, you need to use a personal access token (see [this github documentation](https://docs.github.com/en/github/authenticating-to-github/accessing-github-using-two-factor-authentication#using-two-factor-authentication-with-the-command-line)). Alternatively, you [can connect with SSH](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh) to avoid personal access tokens.
