### ISSUE TITLE
Implement End-to-End Confidentiality for Fabric Networks

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#240]
As per the following spec: https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/models/security/confidentiality.md

**Comment by VRamakrishna** [comment]
@dhinakaran2705 Update the RFC with the set of candidate protocols and our choice for Fabric-Fabric implementation.

**Comment by sanvenDev** [comment]
@VRamakrishna Shall we close this as your PR got merged?

**Comment by VRamakrishna** [comment]
Yes, closing.
