### ISSUE TITLE
Review Cross-Network Operations Models

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#245]
Review and update the following specifications:
- https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/models/ledger/cross-ledger-operations.md
- https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/models/ledger/atomic-cross-ledger-transactions.md

**Comment by dhinakaran2705** [comment]
Suggestion in https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/models/ledger/cross-ledger-operations.md: 

- I was trying to articulate why a unidirectional cross-network dependency only involves "Read triggering Write", and a bidirectional dependency only involves a "Write <-> Write". Read the following, why not a unidirectional dependency be of the form a Write triggering Write?
> We say `Network A depends on Network B` only when there's a write operation in Network A that is influenced by an operation in Network B. So, a bidirectional dependency can only be a write in Network A triggered by a write in Network B and vice versa, simultaneously. On the other hand, a unidirectional dependency can be a read or write in Network B triggering a Write in Network A 

- The following portion seems out of place for this doc, except for explaining the terms in the use-case: "Extrapolating from the above figure, we can now think about a taxonomy of the kinds of records are typically maintained on shared ledger using smart contracts, producing two types:
    Assets: these are digital embodiments of some tangible real-world physical goods that have designated owners and a limited and immutable number of instances; i.e., they cannot be just copied digitally without losing their integrity.
    Data: these are all digital records that are not assets. They can describe properties about entities, things, or the environment, and can be copied arbitrarily while retaining their value."
- It's also possible that we could have more types? It seems like you are differentiating between something that's okay to be copied and something that's not. Why just this dimension and not other dimensions to separate types? 
- It's good to link the use-cases to the type of cross-network dependency. We could also try to articulate if what set of use-cases can be complete for each type of dependency, if that's easy to do.

**Comment by knarayan** [comment]
```
Ledger resources can be classified into data, which can be copied, and assets, which have designated ownership and a limited number of instances
```
Reg data: above describes the allowed operations on data
Reg assets: above describes what an asset is

Add details on what exactly "data" represents, and the allowed operations on assets.

**Comment by knarayan** [comment]
`This will them help` -> `This will then help`?

**Comment by knarayan** [comment]
```
We can reason about the range and exhaustiveness of operations that two distinct shared ledgers, and the networks that maintain them, would like to perform in concert by considering what kinds of resources are present on a ledger and the nature of dependencies between ledgers and the smart contracts deployed on them. This will them help us define the most common and useful cross-network protocols that a platform like Weaver ought to support.
```
The above reflects that `smart contracts` are nothing to do with `cross-network protocols`. However, smart contracts are used to implement these protocols. I guess we need to reflect the same in the text above.

**Comment by VRamakrishna** [comment]
> ```
> Ledger resources can be classified into data, which can be copied, and assets, which have designated ownership and a limited number of instances
> ```
> 
> Reg data: above describes the allowed operations on data Reg assets: above describes what an asset is
> 
> Add details on what exactly "data" represents, and the allowed operations on assets.

@knarayan We aren't trying to limit what the data or asset types can be nor what operations can be performed on them. That is up to the ledger technology and the smart contract system. What I tried to say above was something very generic and which would apply to any smart contract system

**Comment by knarayan** [comment]
`a taxonomy of the kinds of records are typically` -> `a taxonomy of the kinds of records that are typically`

**Comment by knarayan** [comment]
`atomic operations` -> `bidirectional` and `ledger sync` -> `unidirectional`, in the figure?

**Comment by knarayan** [comment]
In https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/models/ledger/atomic-cross-ledger-transactions.md,
(a) `they can eb` -> `they can be`
(b) `bbecause` -> `because`
(c) `or arbitrary assets` -> `of arbitrary assets`

**Comment by VRamakrishna** [comment]
@dhinakaran2705 :

> why not a unidirectional dependency be of the form a Write triggering Write?

Consider what this entails:
1. Ledger A: Write occurs
2. Ledger B -> Ledger A: Read occurs
3. Ledger B: write occurs

In effect, we can break this up into two cross-network concerns:
1. Write in A triggering Read from B
2. Write in B triggered by Read from A

The first step here is effectively a noop in a cross-ledger situation because the first Write was localized to a single ledger and the Read that ensued did not change any state. Only the second step here seems to have an impact, and that is already captured as a Read-triggering-Write in our taxonomy.

Does this make sense?

**Comment by VRamakrishna** [comment]
@dhinakaran2705 :

> The following portion seems out of place for this doc

The logic of this doc is that we are first listing all possible cross-ledger operations, imagining the ledgers as conventional databases. Then we are drawing out a subset of these operations as being highly relevant and very common in blockchain/DLT scenarios and presenting a new taxonomy. Would you rather we moved the latter into a separate doc or did you have something else in mind?

> It's also possible that we could have more types? It seems like you are differentiating between something that's okay to be copied and something that's not. Why just this dimension and not other dimensions to separate types?

Yes, this is exactly it. We have been using these types and this differentiator since the start of this project as it made sense and seemed to cover all the scenarios we are interested in. If you can think of other types or other kinds of differentiators, please suggest them.

> It's good to link the use-cases to the type of cross-network dependency.

Did you mean we should link the labels in the second figure to appropriate labels in the first one, or did you have something else in mind?
