### ISSUE TITLE
Ledger View Event Pub/Sub Protocols

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#264]
- Create structures (protobufs) for event publishing and subscriptions.
- Write specifications for publish and subscribe protocols across two networks.
- Build/adapt modules to realize this feature for Fabric networks (we will add support for other DLTs in a later milestone).
- Augment Fabric testnets and sample apps for event dissemination.
- Add tutorial pages to show users how to test this feature.

**Comment by VRamakrishna** [comment]
Cross-network ledger view event subscriptions may occur at any time. View events are published/disseminated across network boundaries ONLY if subscriptions are already registered. But a subscription need be done only once, and this can result in a future stream of events in the opposite direction. The diagram below illustrates a proposal for a subscription protocol.

![image](https://user-images.githubusercontent.com/14888211/170109812-f4d44207-bd83-47a0-9b1d-593060952f14.png)

**Comment by VRamakrishna** [comment]
A proposal for the ensuring event publish protocol is illustrated in the diaram below.

![image](https://user-images.githubusercontent.com/14888211/170110075-bacd63bd-3d9e-4246-b3c3-2980585e83db.png)

**Comment by VRamakrishna** [comment]
New Weaver components required: _NONE_
Augmentations to existing Weaver components:
- Common protobufs: _see later comment_
- Relays: handle events and event subscriptions
- Fabric driver: add listener for Fabric commitment events (either blocks or transactions), manage event subscriptions, package views and proofs in events
- Fabric Interoperation chaincode: _NONE_
- Fabric Interoperation Node SDK: _OPTIONAL_: library functions for event subscriptions and event handling/dispatch
- Fabric testnets: _NONE_
- Fabric sample chaincode: _NONE_
- Fabric CLI: commands for event subscription and handlers for received events

**Comment by dhinakaran2705** [comment]
The event bus proposal in https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/protocols/events/event-bus.md seems like a generalization of our pub/sub protocol, where you can subscribe for a class of events. 

When saying this, I am thinking of our pub/sub protocol as for subscribing to updates to a particular key or a variable. If you are viewing the pub/sub protocol as means to subscribe to, more generally, any event or a class of events, then the goals of this seems equivalent to the event bus proposal. Some of the terminologies are different. We could update them and merge that to this proposal.

**Comment by VRamakrishna** [comment]
@dhinakaran2705 Yes, that document was originally created as a "vision" document for event management across networks. As you say, the protocol we have described above is a specific instance of how a generic "event bus" would operate: targeted for subscription and publication of a single event triggered by a single ledger commitment action.

We need to update the event bus RFC and create a separate RFC (linked from the former) for the protocol we are trying to design in this epic. Later, we will try to extrapolate from this protocol and write specs for general subscription and publications occurring through the event bus for classes of events.

**Comment by VRamakrishna** [comment]
Below is a proposal for event subscription structures, used in several steps in the subscription flow, and which need to be recognized by drivers, relays, and application agents (whether built on SDK or CLI).

For cross-network view queries, we made a distinction between the structure used by the application ([NetworkQuery](https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/formats/communication/relay.md#networkquery)) to communicate with the relay and the structure used by relays and drivers for their communications ([Query](https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/formats/views/request.md#query)). We will make a similar distinction for the event subscription structure below.

Define `NetworkEventSubscription` in https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/common/protos/networks/networks.proto as follows:
```
message NetworkEventSubscription {
  EventType type = 1;
  string transaction_func = 2;
  repeated string policy = 3;
  string address = 4;
  string requesting_relay = 5;
  string requesting_network = 6;
  string certificate = 7;
  string requestor_signature = 8;
  string requesting_org = 9;
  bool confidential = 10;
}
```

Define `EventType` and `EventSubcription` in https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/common/protos/common/events.proto as follows:
```
enum EventType {
  LedgerState = 0;
  AssetLock = 1;
  AssetClaim = 2;
}

message EventSubscription {
  EventType type = 1;
  string transaction_func = 2;
  repeated string policy = 3;
  string address = 4;
  string requesting_relay = 5;
  string requesting_network = 6;
  string certificate = 7;
  string requestor_signature = 8;
  string request_id = 9;
  string requesting_org = 10;
  bool confidential = 11;
}
```

**Comment by VRamakrishna** [comment]
Both drivers need to maintain maps of event subscriptions, which will be updated in the subscription flow and looked up in the publication flow. We can define these maps in https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/common/protos/driver/driver.proto as follows:
```
message DriverEventDb {
  message EventMatcher {
    EventType type = 0;
    string transaction_func = 1;
  }
  map<EventMatcher, EventSubscription> event_subscriptions = 1;
}
```

**Comment by sanvenDev** [comment]
1. The `EventType` ideally should represent all the events emitted by the source network, so we just need to capture the name of the event that is emitted. To capture the name, `string` type is needed instead of enum.
2. `DriverEventDb` needs a field for Id.

**Comment by VRamakrishna** [comment]
@sanvenDev Regarding the subscription map, I updated the earlier comment. That map needs to be maintained only by the source driver, which needs to create a view request out of an event subscription before attempting to collect proof. (I'll propose another structure for the publishing driver.)

Do we need the source driver to maintain an ID in this map? The map entries are supposed to be long-term, and can trigger several events over the lifetime of the chain.

**Comment by VRamakrishna** [comment]
The destination (subscribing) driver needs to maintain a map of event publications, which will be updated in the subscription flow. We can define this map in https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/common/protos/driver/driver.proto as follows (this includes the structures and field defined in an above comment):
```
message DriverEventDb {
  message EventMatcher {
    EventType type = 0;
    string transaction_func = 1;
  }
  message ContractTransaction {
    string func = 0;
    repeated bytes args = 2;
  }
  message EventPublication {
    oneof publication_target {
      ContractTransaction ctx = 0;
      string app_url = 1;
    }
  }
  map<EventMatcher, EventSubscription> event_subscriptions = 1;
  map<EventMatcher, EventPublication> event_publications = 2;
}
```

(_Note_: the destionation/subscribing driver must maintain both the subscriptions and the publications map whereas the source/publishing driver only needs to maintain the subscriptions map.)

**Comment by knarayan** [comment]
@VRamakrishna, What I feel is that we can have support for specifying the exact event that we want to subscribe for. And this can be achieved by including a `string` field in the `EventSubscription` messages. 

May be later, we can have an additional `event type` specific processing, given that we can partition the events emitted by the network into types.

**Comment by VRamakrishna** [comment]
@knarayan Doesn't the `transaction_func` field serve the purpose you want? And what's wrong with including a placeholder category here? We have an entire category called "ledger views", right? Within a view, we do have names to distinguish one data item of interest from another. I'm following the same logic here.

**Comment by VRamakrishna** [comment]
As far as I can see, we don't need any other data structures. In the publication flow, the publishing driver will generate a regular [View](https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/rfcs/formats/views/definition.md) and send it to the subscribing driver.

**Comment by sanvenDev** [comment]
@VRamakrishna What we meant when we said to use `string` is that, yes source network may potentially emit an unlimited number of events, but adding those events in EventType enum in Weaver source code (protobuf), may be tedious for a dev who is trying to use Weaver as a black box using published packages.  Using `string` is easy to extend. 

That's the only reason, otherwise enum is fine if you think most of the time it may not be required to add more EventTypes by application developer.

**Comment by sanvenDev** [comment]
@VRamakrishna Now I agree that we don't need extra `Id` field, since `EventSubscription` has `request_id` to uniquely identify this subscription. Do you want to call it `request_id`? or some name related to event subscription?

**Comment by sanvenDev** [comment]
@VRamakrishna Also I need to think more on `ContractTransaction`
Do all the details needed to submit a transaction on subscribing network are there?
If we want to use regular View, we need more information like in fabric: which driver, channel, chaincode where to submit the  transaction on subscribing network. 

I think we can use view address and replace index (to indicate which arg needs to be replaced when submitting transaction) instead of `ContractTransaction` object.

**Comment by VRamakrishna** [comment]
We should probably add a field in `EventSubscription` to reference the subscribing driver.

**Comment by sanvenDev** [comment]
```
 message ContractTransaction {
    string func = 0;
    repeated bytes args = 2;
  }
  message EventPublication {
    oneof publication_target {
      ContractTransaction ctx = 0;
      string app_url = 1;
    }
  }
  map<EventMatcher, EventPublication> event_publications = 2;
  ```
  This map can be stored at destination relay instead of destination driver, because it is just routing decision which I think relay should make. Also we want only relay-client communication and not driver-client because driver is assumed to be hidden wrt client (that's what I think).

**Comment by sanvenDev** [comment]
```
message EventSubscriptionState {
  enum STATUS {
    // pending ACK from remote relay
    PENDING_ACK = 0;
    // Received ACK, waiting for data to be sent from remote relay
    PENDING = 1;
    ERROR = 2;
    COMPLETED = 3;
  };
  string request_id = 1;
  STATUS status = 2;
  string error = 3;
}
```

**Comment by sanvenDev** [comment]
`protos/common/events.proto`:
```
enum EventType {
  LedgerState = 0;
  AssetLock = 1;
  AssetClaim = 2;
}

message EventMatcher {
  EventType type = 1;
  string transaction_func = 2;
}
message EventSubscription {
  EventMatcher eventMatcher = 1;
  Query query = 2;
}
message EventSubscriptionState {
  enum STATUS {
    // pending ACK from remote relay
    PENDING_ACK = 0;
    // Received ACK, waiting for event subscription confirmation from remote relay
    PENDING = 1;
    ERROR = 2;
    SUCCESS = 3;
  };
  string request_id = 1;
  STATUS status = 2;
  string respMessage = 3;
  EventMatcher eventMatcher = 3;
  EventPublication eventPublicationSpec = 4;
}

message ContractTransaction {
  string driverId = 1;
  string ledgerId = 2;
  string contractId = 3;
  string func = 4;
  repeated bytes args = 5;
  int replaceArgIndex = 6;
}
message EventPublication {
  oneof publication_target {
    ContractTransaction ctx = 1;
    string app_url = 2;
  }
}
```

`protos/networks/events.proto`
```
message NetworkEventSubscription {
  EventMatcher eventMatcher = 1;
  NetworkQuery query = 2;
  EventPublication eventPublicationSpec = 3;
}
service Event {
  // endpoint for a client to subscribe to event via local relay initiating subscription flow.
  rpc SubscribeEvent(NetworkEventSubscription) returns (common.ack.Ack) {}
  // This rpc endpooint is for polling the local relay for subscription state.
  rpc GetSubscriptionState(GetStateMessage) returns(common.events.EventSubscriptionState) {}
}
```

`protos/relay/events.proto`
```
service EventSubscribe {
  // the requesting relay forwards the request from client as EventSubscription to the src-relay
  rpc SubscribeEvent(common.events.EventSubscription) returns (common.ack.Ack) {}
  // Src-relay based upon query (EventSubscription) forwards the same response (Ack) 
  // from driver to the dest-relay by calling a new endpoint in dest-relay
  rpc SendSubscriptionState(common.ack.Ack) returns (common.ack.Ack) {}
}
```

`protos/driver/events.proto`
```
service EventSubscribe {
  // the src-relay uses this endpoint to forward the event subsctrption request from dest-relay to driver
  rpc SubscribeEvent(common.events.EventSubscription) returns (common.ack.Ack) {}
}
```

**Comment by sanvenDev** [comment]
Updating this data structure:
```
message EventMatcher {
  EventType type = 1;
  string event_name = 2;
  string transaction_func = 3;
}
```
This would help in application developer define sets of events, that a client can target to subscribe. (because of event type doesn't seem to be specific enough to me and Krishna)

**Comment by VRamakrishna** [comment]
Comments on `message EventMatcher`:
- I am not sure what the `event_name` denotes and what it is used for.
- We need an additional field to denote the contract or dapp id. In Fabric, this will be the chaincode ID whose transaction we are trying to match.

**Comment by sanvenDev** [comment]
Updated diagrams:

### Event Subscription
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/17192099/190086030-2b1f1d43-af47-4ea2-b5df-cc34ea0b0b20.png">

### Event Publication:
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/17192099/190086099-03a7551a-11dd-4a9e-919c-042014c73fed.png">

**Comment by VRamakrishna** [comment]
All tasks listed in this epic are complete. The event pub/sub feature can still evolve to offer many more features, but we will open other epics under the Cacti platform for those.
