### ISSUE TITLE
Augment relay to handle event publications

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#268]

**Comment by sanvenDev** [comment]
1. Peer will emit event.
2. Event triggers the callback method `handleEvent` in src-driver.
3. `handleEvent` will fetch the eventMatcher from db matching with event generated, and get all the subscribed queries.
    - For each query, it will invoke an async function `publishEvent` without await.
    - In that async function:
        - Call existing `invoke` function to get the view and the proof, and encapsulate it in `View` (probably create a new function and re-use it in data sharing and event publish).
        - Call the new endpoint in src-relay with the view Payload which also has the requestId (extracted from the stored subscribed queries in database).
 4. The new endpoint at src-relay sends the event data received from the src-driver to the dest-relay via a new endpoint at dest-relay, by fetching dest-relay details from the query/eventSubscription stored in `remote_db`.
 5. The new endpoint at dest-relay will get the event data, fetch the `EventSubscriptionState` from `local_db` and extract the publication target.
     - If publication target is app url, dest-relay sends it to the app_url.
     - Else calls a new endpoint in dest-driver with the event data and `ContractTransaction`. 
 6. In dest-driver, the new endpoint will (using weaver-interop-sdk):
     - extract the interop payload.
     - decrypt if `confidential` is true.
     -

**Comment by sanvenDev** [comment]
RPC endpoint in relay
```
service EventPublish {
  // src-driver forwards the event data to src-relay
  rpc SendDriverEvent(common.state.ViewPayload) returns (common.ack.Ack) {}
  // src-relay will forward event data to dest-relay
  rpc SendEvent(common.state.ViewPayload) returns (common.ack.Ack) {}
}

```

**Comment by VRamakrishna** [comment]
The names `SendState` and `SendDriverState` are a bit confusing. Can we come up with different names, to clearly distinguish the two services?

**Comment by VRamakrishna** [comment]
How about `SendLedgerState` for source and `SendRemoteNotification` for destination?

**Comment by sanvenDev** [comment]
We thought we could re-use the names from data sharing end points (https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/common/protos/relay/datatransfer.proto), as they intend to do the same thing but in the context of event publication, hence the different service name.

**Comment by knarayan** [comment]
We can have a database of the published events at the dest-relay. And the client who ever has previously subscribed for the event, can fetch the list of published events using the request-id.

- We could store the entire published event content in the DB. However, we feel that it is not needed. It's just sufficient to store the Ack.Status|Ack.Message that is received from dest-driver after transaction submission to the app-CC along with the timestamp.

We use request.State to store the status as follows:
- If remote relay response fails, capture that remote-relay failed.
- If dest-driver processing fails, captures that driver failed.
- If dest-driver sends success Ack, then capture that driver processing success.
