### ISSUE TITLE
Manage event subscriptions and publications in Fabric Driver in destination mode

### ISSUE THREAD

**Issue by VRamakrishna** [hyperledger-labs/weaver-dlt-interoperability#271]

**Comment by sanvenDev** [comment]
Dest-relay calls a new endpoint in dest-driver with the event data and ContractTransaction (if driver subscribed).

In dest-driver, the new endpoint will (using weaver-interop-sdk):

    extract the interop payload.
    decrypt if confidential is true.
    send the payload to weaver-interop-cc along with details from ContractTransaction, and submitTransaction.
