### ISSUE TITLE
Asset exchange documentation has a broken link

### ISSUE THREAD

**Issue by hectoratcasper** [hyperledger-labs/weaver-dlt-interoperability#280]
The page below includes a reference to "the test network launched earlier", however when clicking the link a page not found error is display.

URL: 
https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/interop/asset-exchange/

![image](https://user-images.githubusercontent.com/102557486/173495322-1776d072-e4fb-457e-ab2d-d251fe6a8b5c.png)

![image](https://user-images.githubusercontent.com/102557486/173495278-dba9ffa0-1f4b-47e4-9358-05205aac6e06.png)

**Comment by VRamakrishna** [comment]
@hectoratcasper This is weird. If I directly load that URL in the browser, it inserts an extra `interop/` in the path and so you get a 404. But if you get to the "Asset Exchange" page by clicking on the link in the "Overview" page on the left-hand side menu, the link works. Try that out.

I think Docusaurus has issues resolving URLs with relative paths (see https://raw.githubusercontent.com/hyperledger-labs/weaver-dlt-interoperability/main/docs/docs/external/getting-started/interop/asset-exchange.md for an example). We should replace relative paths with absolute paths. I'll open an issue to track.

@sanvenDev FYI.

**Comment by sanvenDev** [comment]
https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/interop/asset-exchange/
This link `/` at the end creates this issue, if you remove that and try open:
https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/interop/asset-exchange
Here everything works fine
