### ISSUE TITLE
Error !!! Create channel failed make: *** [Makefile:35: start-network1-local] Error 1

### ISSUE THREAD

**Issue by Aishwarya-Kulshrestha** [hyperledger-labs/weaver-dlt-interoperability#300]
![Screenshot from 2022-08-01 17-12-55](https://user-images.githubusercontent.com/77093969/182164004-ec9c6e36-c118-4e51-ada6-e488fc51388a.png)
While trying to install Weaver DLT I ran into this problem.

I have tried reinstalling Ubuntu, all prerequisites, changing time (docker showed a different time, thought that might've been the issue).

Any help would be much appreciated.

**Comment by sanvenDev** [comment]
Hi @Aishwarya-Kulshrestha , we have fabric-certs checked-in to the repo for deterministic demonstration. But these fabric-certs have expired, need to create them again, we will fix this as soon as possible.

**Comment by sanvenDev** [comment]
PR #304 will fix this.

**Comment by Aishwarya-Kulshrestha** [comment]
Awesome, thanks!
