### ISSUE TITLE
Getting error while preparing fabric network 1 and fabric network 2 for interoperability

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger-labs/weaver-dlt-interoperability#323]
Hi Team,
I am getting error while cnofiguring network1 and network 2.when i run below command getting error.

**command**: ./bin/fabric-cli configure all network1 network2

**Error**:  Failed to enroll admin, error:%o message=Calling enroll endpoint failed with error [Error: write EPROTO 140649235941248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
], stack=Error: Calling enroll endpoint failed with error [Error: write EPROTO 140649235941248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
]
    at ClientRequest.<anonymous> (/opt/shweta/weaver/weaver-dlt-interoperability/samples/fabric/fabric-cli/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21), errno=-71, code=EPROTO, syscall=write
/opt/shweta/weaver/weaver-dlt-interoperability/samples/fabric/fabric-cli/node_modules/fabric-ca-client/lib/FabricCAClient.js:327
                                const error = Error(`Calling ${api_method} endpoint failed with error [${err}]`);
                  ^
Error: Calling enroll endpoint failed with error [Error: write EPROTO 140649235941248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
]

Kindly help.

Thanks!!!

**Comment by sanvenDev** [comment]
It seems there's something wrong with CA endpoint. Can you check in connection profile and share that here (just CA section)?

**Comment by Shweta-hlf** [comment]
Ca endpoint details present on location "/opt/shweta/weaver/weaver-dlt-interoperability/tests/network-setups/fabric/shared/network1/peerOrganizations/org1.network1.com/connection-org1.json" below.

"   "certificateAuthorities": {
        "ca.org1.network1.com": {
            "url": "https://localhost:7054",
            "caName": "ca-org1",
            "tlsCACerts": {
                "pem": "-----BEGIN CERTIFICATE-----\nMIICFjCCAb2gAwIBAgIUYxHjCF1HdZexrgAM73ec4jdHy8owCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK\nEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt\nY2Etc2VydmVyMB4XDTIyMDgwNDE4MjIwMFoXDTM3MDczMTE4MjIwMFowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl\ncmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy\ndmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE76ubZH/VHJszsYLHVKaUwKBR\nUZv8P+Jq6Op5PeBf02JUKPM15DSF9n56RJq+7mrM9zBzPvBsUySFd+rr/BrsW6NF\nMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE\nFM7HDMehiHl8b92QSMN4Q1FB7JU/MAoGCCqGSM49BAMCA0cAMEQCIH4UJq+qY2OP\n7DzBAwY7woYuy4zoT2kxyiexlix38aY4AiAo+8OKE1wFM+XKLUqI4zzgq2bpg1qb\nU5aIsTpdz3N2tg==\n-----END CERTIFICATE-----\n"
            },
            "httpOptions": {
                "verify": false
            }
        }
    }

"

**Comment by Shweta-hlf** [comment]
I tried with this command : pkill fabric-ca-server -f
and again recreate network .Solves the problem.

Thanks a lot for helping.

**Comment by VRamakrishna** [comment]
Great! Closing this issue now.
