### ISSUE TITLE
Can Weaver be deployed in the k8s network？

### ISSUE THREAD

**Issue by yiqi19940531** [hyperledger-labs/weaver-dlt-interoperability#380]
Can Weaver be deployed in the k8s network？

**Comment by VRamakrishna** [comment]
Weaver consists of a set of components and libraries that can be added on to your existing network. So there is no intrinsic limitation for Weaver to be deployed in a k8s cluster. That said, our samples currently show you how you can install these components (like the relay, driver, and identity agents) in a Docket network (using Compose). We don't have equivalent k8s samples yet. You can check out the [docs](https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/enabling-weaver-network/overview) for guidance. It ought to be fairly easy to translate those suggestions to k8s.

@sanvenDev Do you have any other tips to share?

**Comment by sandeepnRES** [comment]
I'd also suggest the same, I think there are tools available that can convert docker-compose into K8s deployment files.
You can use the Docker images (Relay, Drivers, and IIN-Agent) published on Github. For more info as Rama suggested, please check the docs on how to get the images and to check sample docker-compose files.

**Comment by yiqi19940531** [comment]
Closed.
