### ISSUE TITLE
Error in claiming the remote asset: Illegal base64 character a

### ISSUE THREAD

**Issue by philipbeaucamp** [hyperledger-labs/weaver-dlt-interoperability#407]
Following the Asset Transfer Documentation for a Corda-Corda setup (https://labs.hyperledger.org/weaver-dlt-interoperability/docs/external/getting-started/interop/asset-transfer#2-corda-with-corda) the Asset Transfer flow will fail at line
`val payloadDecoded = Base64.getDecoder().decode(externalStateView.notarizedPayloadsList[0].payload.toByteArray())`
in flow 'ClaimRemoteAsset', with the error message:

'Error in claiming the remote asset: Illegal base64 character a'.

I did not temper with the encoding of the payload in anyway and am strictly following the documentation mentioned above, i.e. runnin the 'claim-remote-asset' command with the correct pledge-id. I can verify the pledge-id in the source network.

Edit: This happens both for the FungibleToken and NFT flow. The response from remote (WriteExternalStateFlows.kt line 133) looks alright in both cases. Here is the response for the NFT case:

`CrsHeyJ0eXBlIjoiYm9uZDAxIiwiaWQiOiJhMTAiLCJvd25lciI6IkxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUo2ZWtORFFWZDFaMEYzU1VKQlowbFJXRVpKYUZsaVZsQkJOREowZUVvMWMyaHdWa2xYYWtGVlFtZG5jV2hyYWs5UVVWRkVRV2RaU1V0dldra0tlbW93UkVGUlkzZE5WRVZNVFVGclIwRXhWVVZDYUUxRFZsWk5lRVZVUVZCQ1owNVdRa0ZqVFVORk5XeGtlVUphWWpOS2NrMVJPSGRFVVZsRVZsRlJTd3BFUVZwUldWaEtNR1ZWUlhkSWFHTk9UV3BOZDA1VVNUVk5SRUYzVFVSQmQxZG9ZMDVOYW1OM1RsUkpkMDFFUVhkTlJFRjNWMnBCZUUxUmMzZERVVmxFQ2xaUlVVZEZkMHBXVlhwRlVrMUJPRWRCTVZWRlFuZDNTVlJ0VmpOSlJteDJZMjF6ZUVSNlFVNUNaMDVXUWtGdlRVSnNRbWhqYmxJMVVWUkJjVTFCVlVjS1FYbDBiR05CVFdoQlEyazNTVVI0TlhsTVkzZFdRVFJhWTJ3eVpETkljbXBhU1dJNWNUVTFVMVZ6UzJWNldFTXdaREl6Y204MFIwcE5TVWRIVFVJd1J3cEJNVlZrUkdkUlYwSkNVbkIwVjFCMVZubG9jMDlHVG5OdVVFODJiVmxKWkdOekwxWmpSRUZRUW1kT1ZraFNUVUpCWmpoRlFsUkJSRUZSU0M5TlFYTkhDa0V4VldSRWQxRkZRWGRKUTJoRVFWUkNaMDVXU0ZOVlJVUkVRVXRDWjJkeVFtZEZSa0pSWTBSQmFrRm1RbWRPVmtoVFRVVkhSRUZYWjBKU2JHTTJRbElLU0hSalNtZHFaV04yVEc5emRUZzBVV3RFZWtZcmVrRlNRbWR2Y2tKblJVVkJXVTlMV1dkRlFrSkJUVU5CVVZsM1JrRlpTVXR2V2tsNmFqQkZRWGRKUndwRFEzRkhVMDAwT1VGM1JVaEJNR2RCVFVWVlEwbFJSREpxVUN0d2NFaHpPVzQ0T1ZVMU0yWkRTMUpGZWs1elZubE5Ra3Q0U2pobE0zTjRNbGsyVmtKSkNrbFJTV2RRU1V4U2IyOXlNR0pDYjBWQ0x6VnBWMWQwZG1Od0wyaHFXblJZTUVGcWJFaHFMMU51V1daMFlWUnpQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHQifRIRQ29yZGFfTmV0d29ya19Qb0MaDkNvcmRhX05ldHdvcmsyIpAHTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVSjVla05EUVZkbFowRjNTVUpCWjBsUllXb3ZkSHBUWTA5UGNUVnRRVFpZVDFvMmVHeFlWRUZWUW1kbmNXaHJhazlRVVZGRVFXZFpTVXR2V2trS2Vtb3dSRUZSWTNkTWVrVk1UVUZyUjBFeFZVVkNhRTFEVWpCSmVFUjZRVTVDWjA1V1FrRmpUVUpyZUhaaWJWSjJZbXBGVUUxQk1FZEJNVlZGUTJkM1J3cFZSMFo1WkVoc1FrMUNORmhFVkVsNFRWUkJlVTVxUVhkTlJFRjNUVVp2V0VSVVNUTk5SRlY1VFVSQmQwMUVRWGROUm05M1RIcEZURTFCYTBkQk1WVkZDa0pvVFVOU01FbDRSSHBCVGtKblRsWkNRV05OUW10NGRtSnRVblppYWtWUVRVRXdSMEV4VlVWRFozZEhWVWRHZVdSSWJFSk5RMjkzUWxGWlJFc3lWbmNLUVhsRlFWWjRSM3BTYldGb2JIRnBXVmt4V0dGbE4yRTBOamxWV1V3d1UxUTBORzE1VjJveGJHNUJSaTk1ZFZkcVoxbHJkMmRaV1hkSVVWbEVWbEl3VHdwQ1FsbEZSa0V4SzJaSWJqVkJjV1UyTVdkNFVsWnlXVmwyWlhCc1dFTlhjVTFCT0VkQk1WVmtSWGRGUWk5M1VVWk5RVTFDUVdZNGQwTjNXVVJXVWpCUUNrSkJVVVJCWjB0RlRVSk5SMEV4VldSS1VWRk5UVUZ2UjBORGMwZEJVVlZHUW5kTlEwMUNPRWRCTVZWa1NYZFJXVTFDWVVGR1JsbFhSbmRDVWpWV1RXZ0thVFpYY2lzdmJHUkVVMWRWVDBSbllrMUNSVWREYVhOSFFWRlJRbWMwY0dsQlVVVkZRWGRKUWtKcVFWVkNaMmR4YUd0cVQxQlJVVVJCWjFsSlMyOWFTUXA2YWpCRVFWRmpSRk5CUVhkU1VVbG9RVkJHYkZobGVVOVFUUzlPVWpBMVkxTk9kMkpZTWxSR2IyMTNWakEwYzA0M1pWcEdjRU5yZWxaNk5VaEJhVUZxQ2s1SGJVNW9TV0psYVd0MFptVm9Zek4wWkZWSGEyWTNRbEkyVW05MlNUUnlUSEZOYkVSdk9FMVpaejA5Q2kwdExTMHRSVTVFSUVORlVsUkpSa2xEUVZSRkxTMHRMUzA9KPzU0aMG`

**Comment by sandeepnRES** [comment]
Hi @philipbeaucamp thanks for pointing it out, a fix will soon be merged with PR #408
