### ISSUE TITLE
Wrong session.receive<T> type in AssetTransferFlow

### ISSUE THREAD

**Issue by philipbeaucamp** [hyperledger-labs/weaver-dlt-interoperability#410]
The responding flow Acceptor(val session: FlowSession) of the Initiator flow of the ClaimRemoteAsset object inside the AssetTransferFlow file (around line 810) receives the wrong enum type "ResponderRole" even though "AssetTransferResponderRole" is being sent in the initiating flow. This will break the flow.

**Comment by sandeepnRES** [comment]
Hi @philipbeaucamp can you explain little bit more about the issue?
Like some steps to reproduce, and what error do you see?

**Comment by philipbeaucamp** [comment]
The steps to reproduce the issue are to simply run the ClaimRemoteAsset
flow with a non-empty observer list or an issuer that is different from our
identity.
The reason you might have overlooked this issue is because your test flows
do not call the responder flow.

The error will happen on line 813. I don't have the exact error message
anymore, but it will be a type of deserialization error since you're trying
to deserialize an object of type "ResponderRole" whereas an object of type
"AssetTransferResponderRole" on line 788 and 797 was sent.

**Comment by philipbeaucamp** [comment]
This issue is easily fixed by simply replacing "ResponderRole" with
"AssetTransferResponderRole" in the responder flow by the way.
I would have posted a PR but I don't have the right credentials.

**Comment by philipbeaucamp** [comment]
Thanks for the information. I created the PR here https://github.com/hyperledger-labs/weaver-dlt-interoperability/pull/411

Are you able to make a comment about how different the "Weaver" part of HyperledgerCacti is from this repository? I understand that the project originated from a merge between Weaver and Cactus and am wondering how different the current status is.

**Comment by sandeepnRES** [comment]
Thanks for the PR @philipbeaucamp . Mostly right now both codebases are same. But there are some changes that doesn't affect any protocol or logic, just package management tasks. But there were some fixes made in Cacti's weaver that isn't made here.

**Comment by sandeepnRES** [comment]
#411 fixes this
