### ISSUE TITLE
Build Failed in corda interopapp directory

### ISSUE THREAD

**Issue by thobbyAk** [hyperledger-labs/weaver-dlt-interoperability#441]
I am having a build failed issue when I try to build the Corda Interop app locally.
![Screenshot 2024-04-05 at 19 49 48](https://github.com/hyperledger-labs/weaver-dlt-interoperability/assets/71441407/29c94ee6-a667-41fb-beec-8cedd355a66d)

**Comment by VRamakrishna** [comment]
@thobbyAk We haven't actively developed in this code repository for over a year now. In 2022-23, this project was merged into Hyperledger Cacti, which is where we are currently maintaining it. See https://www.hyperledger.org/blog/2022/11/07/introducing-hyperledger-cacti-a-multi-faceted-pluggable-interoperability-framework and https://www.hyperledger.org/blog/hyperledger-cacti-a-general-purpose-modular-interoperability-framework-moves-to-graduated-status for info.

To test and use the latest Weaver features within Cacti, go to the Cacti repository (https://github.com/hyperledger/cacti), where the Weaver code lies in a subfolder at present (https://github.com/hyperledger/cacti/tree/main/weaver). Follow the instructions from the Cacti-Weaver docs (which resemble the Weaver docs but with updated info): https://hyperledger.github.io/cacti/weaver/getting-started/guide/.

If you see the same error there (or any other error), please open a Cacti issue: https://github.com/hyperledger/cacti/issues.

**Comment by VRamakrishna** [comment]
@thobbyAk FYI, the errors you see here are because the Corda package repositories have been replaced in the past year. The Weaver code within Cacti has been updated suitably, but this repository has not. Consider this repository to be deprecated. We will be making a few updates here shortly and then archiving it. Hyperledger Cacti is the future of this project.
