### ISSUE TITLE
Add owner parameter to GetTotalFungibleLockedAsset()

### ISSUE THREAD

**Issue by ermyas** [hyperledger-labs/weaver-dlt-interoperability#51]
The `GetTotalFungibleLockedAsset()` method is meant to retrieve the total locked fungible assets of a given type for a given entity. However, the current method signature does not accept the owner field and implicitly assumes that the owner will be the identity submitting the transaction. Since this might not always be the case, we should add a parameter for the owning identity, for which this query is to be performed.

**Comment by VRamakrishna** [comment]
This function was eliminated as it was deemed unnecessary. Fungible asset counts are being accounted for in the application chaincode instead. Fungible asset contracts are uniquely identified by a dynamically generated id.
